# Site settings
title: Kharis Sulistiyono
email: kharisulistiyo@gmail.com
description: WordPress Theme and Plugin Developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # http://yourdomain.com the base hostname & protocol for your site
twitter_username: kharissulistiyo
github_username:  kharissulistiyo

# Build settings
markdown: redcarpet
